### PR TITLE
4xx status codes are not errors in the context of telemetry

### PR DESCRIPTION
**Pull request by tj-cisco**
4xx status codes should not be considered an error in the context of telemetry.  These are normal status codes for every day operations, especially in the context of REST apis.

### CODE REVIEW

**Comment by jjatria** [comment]
Thanks for the contribution!

Do you have any documentation to support this?

I found some conflicting examples when looking at other instrumentations. See for example [the `net/http` one for Ruby](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/net_http/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb#L81), where 400 and higher are treated as errors, but [the `sinatra` one](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb#L34) does what you suggest and only treats server errors as errors.

**Comment by jjatria** [comment]
Ah, this seems to be the relevant bit:

> [Span Status](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.31.0/specification/trace/api.md#set-status) MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges, unless there was another error (e.g., network error receiving the response body; or 3xx codes with max redirects exceeded), in which case status MUST be set to Error.
>
> For HTTP status codes in the 4xx range span status MUST be left unset in case of SpanKind.SERVER and MUST be set to Error in case of SpanKind.CLIENT.

Source: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#status

But in this case the PR will need to be amended, because with a 4xx we have to leave the status unset, not set it to OK. Do you want to make that change?

**Comment by jjatria** [comment]
See also the fix for a similar issue in the Mojolicious plugin I pushed out just now: https://github.com/jjatria/mojolicious-plugin-opentelemetry/commit/3dc6b0dacb6a767cb2f7088dec7f98fb292fbe41

**Comment by tj-cisco** [comment]
The mojolicious change sets the span status to OK for 4xx errors, which is the same as this change.

**Comment by jjatria** [comment]
I don't think you read that correctly:
``` perl
if ( $code < 400 ) {
    $span->set_status(SPAN_STATUS_OK);
}
elsif ( $code >= 500 ) {
    $span->set_status(SPAN_STATUS_ERROR);
}
```
It sets it to OK if the code is < 400, and to error if it is >= 500.

**Comment by tj-cisco** [comment]
Indeed you're correct, I need more coffee. I will make this PR match.

**Comment by jjatria** [comment]
I've commited this as 4d0a1cf54fcc699c6e555b2d24fc7f1e6d1a8089 with some small changes. I'll push this to CPAN shortly. Thanks again for raising this issue!

**Pull request closed without merging**
